# SPDX-License-Identifier: Apache-2.0
"""Generate claims/register.yaml FROM the evidence artifacts.

Every number in the register is read from an artifact produced by a
deterministic script; every literature sha256 is computed from the committed
extract. Nothing is typed from memory — the register is a projection of the
evidence, which is the only honest direction.

    python3 build_register.py
"""
from __future__ import annotations

import hashlib
import json
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def block(key: str, text: str, indent: str = "    ") -> str:
    lines = textwrap.wrap(" ".join(str(text).split()), width=72)
    body = "\n".join(f"{indent}  {ln}" for ln in lines)
    return f"{indent}{key}: >\n{body}\n"


def main() -> int:
    taut = json.loads((ROOT / "artifacts" / "tautologies.json").read_text())
    hilb = json.loads((ROOT / "artifacts" / "hilbert.json").read_text())
    nums = json.loads((ROOT / "artifacts" / "numbers.json").read_text())
    refs = json.loads((ROOT / "research" / "references.json").read_text())

    out = ["---",
           "# GENERATED by build_register.py from the evidence artifacts —",
           "# regenerate rather than hand-edit; numbers come from evidence only.",
           "", 'schema_version: "1"', "", "claims:", ""]

    seed_caveat = ("Formula seeded from model knowledge (Claude Fable) and "
                   "trusted ONLY because the exhaustive truth-table checker — "
                   "a complete decision procedure for propositional logic — "
                   "verified it under every assignment. Scope is exactly the "
                   "stated formula.")
    for cid, rec in sorted(taut["theorems"].items()):
        out.append(f"  - id: {cid}")
        out.append(block("statement",
                         f"The propositional formula '{rec['name']}' is a "
                         f"tautology, machine-verified under all "
                         f"{rec['n_assignments_checked']} truth assignments "
                         f"of its {rec['n_atoms']} atoms.").rstrip())
        out.append("    evidence_level: machine_checked")
        out.append("    artifact:")
        out.append('      - "artifacts/tautologies.json"')
        out.append("    metrics:")
        out.append(f"      n_assignments_checked: {rec['n_assignments_checked']}")
        out.append(block("caveat", seed_caveat).rstrip())
        out.append('    reproduce: "python3 theorems/evidence_tautologies.py"')
        out.append("")

    hs = hilb["derivations"]["hypothetical_syllogism"]
    out.append("  - id: THM-HS-001")
    out.append(block("statement",
                     f"Hypothetical syllogism — (q->r) -> ((p->q) -> (p->r)) — "
                     f"derives in the Lukasiewicz system (A1-A2, modus ponens) "
                     f"in {hs['steps_verified']} steps; every step "
                     f"machine-verifies as an axiom instance or MP "
                     f"application.").rstrip())
    out.append("    evidence_level: machine_checked")
    out.append("    artifact:")
    out.append('      - "artifacts/hilbert.json"')
    out.append('      - "theorems/proofs/hypothetical_syllogism.json"')
    out.append(f"    n: {hs['steps_verified']}")
    out.append("    metrics:")
    out.append(f"      steps_verified: {hs['steps_verified']}")
    out.append(block("caveat",
                     "Derivation seeded from model knowledge (Claude Fable); "
                     "trusted only because the fail-closed Hilbert checker "
                     "verified every step. The checker is a byte-copy of the "
                     "one behind vericlaim CLAIM-THM-001 (~100 lines, "
                     "property-tested), not an independently audited "
                     "kernel.").rstrip())
    out.append('    reproduce: "python3 theorems/evidence_hilbert.py"')
    out.append("")

    bounded = [
        ("NUM-PRIME-001",
         f"There are exactly {nums['primes_below_limit']} primes below "
         f"{nums['prime_limit']}.",
         {"primes_below_limit": nums["primes_below_limit"]},
         "Exact exhaustive count (sieve of Eratosthenes) — scope is the "
         "stated bound only."),
        ("NUM-TWIN-001",
         f"There are exactly {nums['twin_prime_pairs_below_limit']} twin-prime "
         f"pairs (p, p+2) with p+2 < {nums['prime_limit']}.",
         {"twin_prime_pairs_below_limit": nums["twin_prime_pairs_below_limit"]},
         "Exact exhaustive count; says nothing about the twin-prime "
         "conjecture."),
        ("NUM-GOLD-001",
         f"Goldbach's conjecture holds for every even number from 4 to "
         f"{nums['goldbach_limit']}: all "
         f"{nums['goldbach_even_numbers_verified']} even numbers in range "
         f"decompose as a sum of two primes.",
         {"goldbach_even_numbers_verified": nums["goldbach_even_numbers_verified"]},
         "A BOUNDED verification, not a proof of the conjecture — the claim's "
         "scope ends at the stated limit, full stop."),
    ]
    for cid, stmt, metrics, cav in bounded:
        out.append(f"  - id: {cid}")
        out.append(block("statement", stmt).rstrip())
        out.append("    evidence_level: machine_checked")
        out.append("    artifact:")
        out.append('      - "artifacts/numbers.json"')
        out.append("    metrics:")
        for k, v in metrics.items():
            out.append(f"      {k}: {v}")
        out.append(block("caveat", cav + " Values computed at evidence time, "
                         "never recalled from model memory.").rstrip())
        out.append('    reproduce: "python3 numbers/evidence_numbers.py"')
        out.append("")

    for rid, rec in sorted(refs["verified"].items()):
        extract = ROOT / rec["extract"]
        sha = hashlib.sha256(extract.read_bytes()).hexdigest()
        out.append(f"  - id: {rid}")
        out.append(block("statement",
                         f"{rec['title']} ({rec['year']}) is a "
                         f"registrar-verified work ({rec['work_id']}) whose "
                         f"abstract extract is preserved hash-locked in this "
                         f"repository. Curation note: {rec['why']}.").rstrip())
        out.append("    evidence_level: theoretical")
        out.append("    artifact:")
        out.append(f'      - "{rec["extract"]}"')
        out.append(block("caveat",
                         "A bibliographic claim only: the registrar record "
                         "exists and the committed extract is hash-locked. "
                         "Asserts NOTHING about the correctness of the work's "
                         "results; the arXiv record is a preprint snapshot — "
                         "a peer-reviewed venue version may exist but is not "
                         "asserted. Title was Fable-seeded; metadata is "
                         "registrar-fetched.").rstrip())
        out.append("    literature:")
        out.append(f'      - source: "{rec["work_id"]} — {rec["url"]}"')
        out.append(f"        sha256: {sha}")
        out.append(f'        file: "{rec["extract"]}"')
        out.append("")

    (ROOT / "claims" / "register.yaml").write_text("\n".join(out) + "\n",
                                                   encoding="utf-8")
    n = len(taut["theorems"]) + 1 + len(bounded) + len(refs["verified"])
    print(f"[OK] register generated with {n} claims from evidence artifacts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
