# SPDX-License-Identifier: Apache-2.0
# GENERATED by vericlaim use_code — do not edit. This test binds the vendored
# code under lib/claim_thm_001/ to bundle 202a3798de38 (claim CLAIM-THM-001): the code you run is
# byte-exact the code that produced the claim's evidence. If you need to
# change the vendored code, you are FORKING it: delete this test and own the
# divergence explicitly.
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BINDING = ROOT / "lib/claim_thm_001" / "BINDING.json"


def test_vendored_code_matches_bundle_manifest():
    binding = json.loads(BINDING.read_text())
    for rel, expected in sorted(binding["files"].items()):
        p = ROOT / "lib/claim_thm_001" / rel
        assert p.is_file(), f"vendored file missing: {rel}"
        actual = hashlib.sha256(p.read_bytes()).hexdigest()
        assert actual == expected, (
            f"{rel} was edited after vendoring (hash {actual[:12]} != "
            f"bundle {expected[:12]}) — fork explicitly by deleting "
            f"tests/test_bundle_binding_claim_thm_001.py or re-vendor the original")
